contato/urls.py
from django.urls import path
from .views import index, contato, buscar, criacao, atualizacao, deletar, registro, login_view, logout_view, atualizar_usuario

app_name = 'contato'

urlpatterns = [
    path('', index, name="index"),
    path('buscar/', buscar, name="buscar"),

    # Contato (CRUD)
    path('contato/<int:contato_id>/detalhe/', contato, name="contato"),
    path('contato/criacao/', criacao, name="criacao"),
    path('contato/<int:contato_id>/atualizacao/', atualizacao, name="atualizacao"),
    path('contato/<int:contato_id>/deletar/', deletar, name="deletar"),

    # usuario

    path('usuario/registro/', registro, name='registro'),
    path('usuario/login/', login_view, name='login'),
    path('usuario/logout/', logout_view, name='logout'),
    path('usuario/atualizacao_usuario/', atualizar_usuario, name='atualizar_usuario'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contato.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

contato/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Categoria(models.Model):
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
    nome = models.CharField(max_length=125)

    def __str__(self):
        return self.nome


class Contato(models.Model):
    primeiro_nome = models.CharField(verbose_name='Nome', max_length=100)
    segundo_nome = models.CharField(max_length=150, verbose_name='Sobrenome')
    telefone = models.CharField(max_length=50)
    email = models.EmailField(max_length=256, blank=True)
    data_criacao = models.DateTimeField(default=timezone.now)
    descricao = models.TextField(blank=True)
    visivel = models.BooleanField(default=True)
    imagem = models.ImageField(blank=True, upload_to='imagens/%Y/%m/')
    categoria = models.ForeignKey(Categoria,
                                  on_delete=models.SET_NULL,
                                  blank=True, null=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __str__(self):
        return self.primeiro_nome

contato/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Contato

from django.contrib.auth import password_validation



class ContatoForm(forms.ModelForm):

    imagem = forms.ImageField(
        widget=forms.FileInput(
            attrs = {
                'accept': 'imagem/*',
            }
        )
    )

    class Meta:
        model = Contato
        fields = ('primeiro_nome', 'segundo_nome', 'imagem', 'telefone', 'email', 'categoria', 'descricao')
 
        # widgets = {'primeiro_nome': forms.PasswordInput(attrs=
        # {'class': 'classe-a classe-b','placeholder': 'Infome seu nome', }), }

    def clean(self):
        cleaned_data = self.cleaned_data
        primeiro_nome = cleaned_data.get('primeiro_nome')
        segundo_nome = cleaned_data.get('segundo_nome')
        
        if primeiro_nome == segundo_nome:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )

            self.add_error('primeiro_nome', msg)
            self.add_error('segundo_nome', msg)
        return super().clean()

    def clean_first_name(self):
        primeiro_nome = self.cleaned_data.get('primeiro_nome')

        if primeiro_nome == 'ABC':
            self.add_error(
                'primeiro_nome',
                ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )

        return primeiro_nome


class RegistroForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2'
        )
    
    def clean_email(self):
        # Aqui é para não deixar terem e-mails iguais.
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Jé existe este e-mail', code='invalid')
                )

        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if not password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )
        
        return password1


class AtualizacaoRegistro(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )



    class Meta:
        model = User
        fields = (
                'first_name', 'last_name', 'email',
                'username',
            )

contato/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    return render(request, 'contato/index.html')

contato/views/contato_formulario.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from contato.forms import ContatoForm
from contato.models import Contato


app_name = 'contato'

@login_required(login_url='contato:login')
def criacao(request):
    form_action = reverse('contato:criacao')

    if request.method == 'POST':
        form = ContatoForm(request.POST, request.FILES )

        contexto = {
            'form': form,
            'form_action': form_action,
            }

        if form.is_valid():
            contato = form.save(commit=False)
            contato.owner = request.user
            contato.save()
            return redirect('contato:atualizacao', contato_id=contato.pk)

        return render(request, 'contato/criacao.html', contexto)
    
    contexto = {
        'form': ContatoForm(),
        'form_action': form_action,
    }

    return render(request, 'contato/criacao.html', contexto)


@login_required(login_url='contato:login')
def atualizacao(request, contato_id):
    contato = get_object_or_404(Contato, pk=contato_id, visivel=True, owner=request.user)
    form_action = reverse('contato:atualizacao', args=(contato_id,))

    if request.method == 'POST':
        form = ContatoForm(request.POST, request.FILES, instance=contato)

        contexto = {
            'form': form,
            'form_action': form_action,
            }

        if form.is_valid():
            contato = form.save()
            return redirect('contato:atualizacao', contato_id=contato.pk)

        return render(request, 'contato/criacao.html', contexto)
    
    contexto = {
        'form': ContatoForm(instance=contato),
        'form_action': form_action,
    }

    return render(request, 'contato/criacao.html', contexto)

@login_required(login_url='contato:login')
def deletar(request, contato_id):
    contato  = get_object_or_404(
        Contato, pk=contato_id, visivel=True,
        owner=request.user
    )

    confirmacao = request.POST.get('confirmacao', 'nao')
    if confirmacao == 'sim':
        contato.delete()
        return redirect('contato:index')

    print(confirmacao)

    # contato.delete()
    # return redirect('contato:index')

    return render(
        request,
        'contato/contato.html',
        {
            'contato':contato,
            'confirmacao': confirmacao,
        }
    )

contato/views/contato_view.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from contato.models import Contato
from django.db.models import Q
# Create your views here.

def index(request):
    contatos = Contato.objects.all().filter(visivel=True).order_by('-id')

    paginator = Paginator(contatos, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'site_titulo': 'Contatos '
    }
    
    return render(request, 'contato/index.html', context)


def buscar(request):
    valor_de_busca = request.GET.get('q', '').strip()

    if valor_de_busca == '':
        return redirect('contato:index')

    # filtando nome pela parada de busca
    # Se utiliar vírgua é "E" como Q e o | eu crio um "ou"
    contatos = Contato.objects \
    .filter(visivel=True) \
    .filter(
        Q(primeiro_nome__icontains=valor_de_busca) | 
        Q(segundo_nome__icontains=valor_de_busca) |
        Q(telefone__icontains=valor_de_busca) |
        Q(email__icontains=valor_de_busca)
    ).order_by('-id')

    paginator = Paginator(contatos, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_titulo': 'Contatos '
    }
    
    return render(request, 'contato/index.html', context)



def contato(request, contato_id):
    #contato = Contato.objects.get(pk=contato_id)
    contato = get_object_or_404(Contato, pk=contato_id, visivel=True)
    
    context = {
        'contato': contato,
        'site_titulo': f'{contato.primeiro_nome} {contato.segundo_nome}'
    }
    
    return render(request, 'contato/contato.html', context)

contato/views/usuario_view.py
from django.shortcuts import render, redirect
from contato.forms import RegistroForm, AtualizacaoRegistro
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from django.contrib.auth.decorators import login_required

def registro(request):
    form = RegistroForm()

    if request.method == 'POST':
        form = RegistroForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request,'Usuário registrado com sucesso!')
            return redirect('contato:index')
    


    context = {
        'form': form
    }
    
    return render(request, 'contato/registro.html', context)


def login_view(request):
    form = AuthenticationForm(request, data=request.POST)

    if request.method == 'POST':
        if form.is_valid():
            usuario = form.get_user()
            messages.success(request, 'Logado com sucesso.')
            auth.login(request, usuario)
            return redirect('contato:index')
        
    messages.error(request, 'Login inválido.')


    return render(request,'contato/login.html', {'form': form})


@login_required(login_url='contato:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contato:login')

@login_required(login_url='contato:login')
def atualizar_usuario(request):
    form = AtualizacaoRegistro(instance=request.user)
    if request.method != 'POST':
        return render(request,'contato/registro.html', {'form': form})
    

    form = AtualizacaoRegistro(data=request.POST, instance=request.user)
    if not form.is_valid():
        return render(request,'contato/registro.html', {'form': form})
    
    form.save()
    return render(request,'contato/registro.html', {'form': form})

contato/templates/contato/contato.html
{% extends 'global/base.html' %}

{% block conteudo %}

    <div class="sigle-contact">
        <h1 class="sigle-contact-name">
            {{ contato.primeiro_nome }} {{ contato.segundo_nome }}
        </h1>

        <p><b>ID:</b> {{contato.id}}</p>
        <p><b>E-mail:</b> {{contato.email}}</p>
        <p><b>Telefone:</b> {{contato.telefone}}</p>
        <p><b>Data de criação:</b> {{contato.data_criacao}}</p>
        <p><b>Descrição:</b> {{contato.descricao}}</p>
        <p><b>Categoria:</b> {{contato.categoria.nome}}</p>

        {% if contato.imagem %}
            <p>
                <img src="{{ contato.imagem.url }}" alt="{{ 'contato.primeiro_nome' }} {{ 'contato.segundo_nome' }}">
            </p>
        {% endif %}
        
        {% if user == contato.owner %}
            <div class="contact-links">
                <a class="btn btn-link" href="{% url 'contato:atualizacao' contato.pk%}">Atualizar</a>

                <form action=" {% url 'contato:deletar' contato.id %} " method="POST">
                    {% csrf_token %}

                    {% if confirmacao == 'nao'  %}
                        <input type="hidden" name="confirmacao" value="sim">
                        <button class="btn btn-link btn-delete " type="submit">Confirmar?</button>    
                    {% else %}
                        <button class="btn btn-link btn-delete " type="submit">Deletar</button>
                    {% endif %}
    
                </form>
            </div>
        {% endif %}
        

    </div>


{% endblock conteudo %}

contato/templates/contato/criacao.html
{% extends 'global/base.html' %}


{% block conteudo %}

    <div class="form-wrapper">
        <h2>Contato</h2>
        <form action="{% url 'contato:criacao' %}" method="POST" enctype="multipart/form-data">

            {% csrf_token %}

        
            <!--Aqui é pegando o formulário toda de uma vez  {{ form.as_p }}   -->
            <div class="form-content"></div>
                {% for campo in form  %}
                
                    <div class="form-group">
                    <label for="{{ campo.id_for_label }}"> {{campo.label.capitalize}} </label>
                    {{campo}}
                    {{campo.errors}}
                    </div>
                
                {% endfor %}
            </div>   
           

            
            

            <div class="form-content">
                <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
                </div>
            </div>

        </form>
    </div>
    
{% endblock  %}

contato/templates/contato/index.html
{% extends 'global/base.html' %}

{% block conteudo %}

    {% if page_obj %}

        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contatos
                </caption>
                

                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">Nome</th>
                        <th class="table-header">Sobrenome</th>
                        <th class="table-header">Telefone</th>
                        <th class="table-header">E-maiil</th>
                    </tr>
                </thead>

                <tbody>
                    {% for contato in page_obj  %}
                    
                        <tr class="table-row">
                            <td class="table-cel">
                                <a class="table-link" href="{% url 'contato:contato' contato.id %}"> {{ contato.id }} </a>
                            </td>

                            <td class="table-cel">
                                {{ contato.primeiro_nome }}
                            </td>

                            <td class="table-cel">
                                {{ contato.segundo_nome }}
                            </td>

                            <td class="table-cel">
                                {{ contato.telefone }}
                            </td>

                            <td class="table-cel">
                                {{ contato.email }}
                            </td>


                        </tr>
                    

                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}

    

    <div class="sigle-contact">
        <h1 class="sigle-contact-name">
            Não foi possível encontar
        </h1>    
    </div>

    {% endif %}    




{% endblock conteudo %}

contato/templates/contato/login.html
{% extends 'global/base.html' %}

{% block conteudo %}

    <div class="form-wrapper">

        {% if user.is_authenticated %}
            <p>Você está logado como {{user.username.capitalize}}</p>
            <p>Clique<a href="{% url 'contato:logout' %}">aqui</a> para sair!</p>
            
        {% else %}
        
            <form action="{{ form_action }}" method="POST">
                {% csrf_token %}
                <div class="form-content"></div>
                    {% for campo in form  %}
                        <div class="form-group">
                        <label for="{{ campo.id_for_label }}"> {{campo.label}} </label>
                        {{campo}}   
                        {{ campo.errors }}
                        </div>
                    {% endfor %}
                </div>   
            
                <div class="form-content">
                    <div class="form-group">
                    <button class="btn" type="submit">Logar</button>
                    </div>
                </div>

        </form>


        {% endif %}

        
    
    </div>
    
{% endblock  %}

contato/templates/contato/registro.html
{% extends 'global/base.html' %}

{% block conteudo %}

    <div class="form-wrapper">
        <h2>Registro</h2>
        <form action="{{ form_action }}" method="POST">

            {% csrf_token %}

            <div class="form-content"></div>

                {% for campo in form  %}
                
                    <div class="form-group">
                    <label for="{{ campo.id_for_label }}"> {{campo.label}} </label>
                    {{campo}}   
                    {{ campo.errors }}
                    </div>

                {% endfor %}
            </div>   
           
            <div class="form-content">
                <div class="form-group">
                <button class="btn" type="submit">Enviar</button>
                </div>
            </div>

        </form>
    </div>
    
{% endblock  %}